"use strict";

const DEFAULTS = {
  HOUSE_STYLE_ID: "house-nextgen-exec",
  WORKFLOW: "direct-html",
  VARIANT: 1,
  REFERENCE_MODE: "off",
  PAGE_MODE: "default",
  REQUEST_TIMEOUT_MS: 240000,
  EXTREME_REQUEST_TIMEOUT_MS: 420000,
  LLM_GENERATE_TIMEOUT_MS: 180000,
  LLM_REPAIR_TIMEOUT_MS: 40000,
  TOTAL_LLM_BUDGET_MS: 210000,
  ATTEMPT_TIMEOUT_MS: 180000,
  MIN_LLM_REMAINING_BUDGET_MS: 5000,
  RETRY_ON_TIMEOUT_ENABLED: true,
  RETRY_COMPACT_TOTAL_BUDGET_MS: 90000,
  RETRY_COMPACT_ATTEMPT_TIMEOUT_MS: 60000,
  RETRY_COMPACT_MIN_REMAINING_BUDGET_MS: 4000,
  RETRY_COMPACT_MAX_TEXT_CHARS: 7000,
  EXTREME_TOTAL_LLM_BUDGET_MS: 255000,
  EXTREME_ATTEMPT_TIMEOUT_MS: 210000,
  EXTREME_MIN_LLM_REMAINING_BUDGET_MS: 5000,
  EXTREME_MODEL_TIMEOUTS_MS: {
    "gemini-2.5-flash": 180000,
    "gemini-3-flash-preview": 45000,
  },
  EXTREME_RETRY_COMPACT_TOTAL_BUDGET_MS: 120000,
  EXTREME_RETRY_COMPACT_ATTEMPT_TIMEOUT_MS: 80000,
  EXTREME_RETRY_COMPACT_MIN_REMAINING_BUDGET_MS: 4000,
  EXTREME_RETRY_COMPACT_MAX_TEXT_CHARS: 9000,
  MODEL_CANDIDATES: ["gemini-2.5-flash", "gemini-3-flash-preview"],
  MODEL_TIMEOUTS_MS: {
    "gemini-2.5-flash": 150000,
    "gemini-3-flash-preview": 30000,
  },
  MAX_COMBINED_CHARS: 20000,
  MIN_SLIDES_REQUIRED: 2,
  RECOMMENDED_SLIDES: 6,
  CREATIVE_MODE_DEFAULT: true,
};

module.exports = { DEFAULTS };
